version: 0.0
os: linux
files:
  - source: frontend/
    destination: /var/www/html
    fileExistsBehavior: OVERWRITE

  - source: backend/
    destination: /opt/app
    fileExistsBehavior: OVERWRITE

  - source: scripts/
    destination: /opt/app/scripts/
    fileExistsBehavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/reload_nginx.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
