version: 0.2

phases:
  install:
    commands:
      - echo Installing backend dependencies...
      - npm install --prefix backend
  build:
    commands:
      - echo Build backend started on `date`
      - chmod +x scripts/*.sh
      - npm run build --prefix backend

artifacts:
  files:
    - appspec-backend.yml
    - backend/**/*
    - scripts/**/*
